# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tick-list?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai&tinyInt1isBit=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  mail:
    host: smtp.163.com
    # 在使用时，username和password一定要修改为自己的，否则发送邮件功能无法使用，不影响其他功能
    username: dxylovelq@163.com
    password: SJPLBCHBKHIIQCLF
    default-encoding: UTF-8
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.socketFactory.port: 465
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.smtp.socketFactory.fallback: false
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
  http:
    multipart:
      enable: true
redis:
  database: tick-list
  securityCode: securityCode
  expire: 10000
# 邮件发件人
mail:
  from: dxylovelq@163.com

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 逻辑已删除值
      logic-delete-value: 0
      # 逻辑未删除值
      logic-not-delete-value: 1
  mapper-locations: classpath*:/mapper/**Mapper.xml
# token令牌
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌秘钥
  secret: (EMOK:)_$^11244^%$_(IS:)_@@++--(COOL:)_++++_.sds_(GUY:)
  # 令牌有效期
  expireTime: 3600000

server:
  port: 8888
# 取消邮件的健康检查机制，不让其报错，又很好地保护了个人的SMTP码泄漏
management:
  health:
    mail:
      enabled: false

cos:
  secretId: AKIDlLfmdDWYKq42kAJBnriKgneGcleIgogI
  secretKey: NVO1OVMyKQIuGMCn8D1atwjHZbOvDH5d
  # regionName只填写这个，小心，不然上传失败
  regionName: ap-nanjing
  # bucketName一定是桶名称加上AppId
  bucketName: tick-list-1301888953
  imageAddr: https://tick-list-1301888953.cos.ap-nanjing.myqcloud.com/