# DataSource Config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/our-task-test?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai&tinyInt1isBit=false&allowPublicKeyRetrieval=true
    username: daxingyong
    password: daxingyong
# 自定义redis key
redis:
  database: "our-task-test"
  key:
    category: "category"
    user: "user"
    task: "task"
  expire:
    common: 43200 # 12小时
