# DataSource Config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/our-task?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai&tinyInt1isBit=false&allowPublicKeyRetrieval=true
    username: root
    password:
# 自定义redis key
redis:
  database: "our-task"
  key:
    category: "category"
    user: "user"
    task: "task"
    label: "label"
  expire:
    common: 86400 # 24小时